[package]
name = "proofs-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proofs = { path = "../proofs" }
datafusion = "11.0.0"
tokio = { version = "1", features = ["full"] }
