[profile.default]
src = "src"
out = "out"
solc = "0.8.28"
libs = ["dependencies"]
no-match-path = "**/*.presl"
no-match-coverage = "presl"

[doc]
ignore = ["**/*.presl"]

[dependencies]
forge-std = "1.9.5"

[soldeer]
remappings_generate = true
