[workspace]
members = ["crates/proofs", "crates/proofs-sql", "benches/provable_sql"]

[workspace.package]
edition = "2021"
exclude = ["**/.gitignore", ".gitignore"]
repository = "https://github.com/spaceandtimelabs/proofs"
version = "0.0.0" # DO NOT CHANGE THIS LINE! This will be automatically updated

[workspace.dependencies]
ark-curve25519 = { version = "0.4.0" }
ark-ff = { version = "0.4.0" }
ark-poly = { version = "0.4.0" }
ark-serialize = { version = "0.4.0" }
ark-std = { version = "0.4.0" }
arrayvec = { version = "0.7" }
arrow = { version = "36.0" }
bit-iter = { version = "1.1.1" }
blake3 = { version = "1.3.3" }
blitzar = { package = "blitzar", version = "8.0.0", registry = "artifactory" }
bumpalo = { version = "3.11.0" }
byte-slice-cast = { version = "1.2.1" }
curve25519-dalek = { version = "3" }
derive_more = { version = "0.99" }
dyn_partial_eq = { version = "0.1.2" }
half = { version = "=2.2.1" } # This can be removed when we bump to rust version 1.70
hashbrown = { version = "0.11.2" }
indexmap = { version = "1.9" }
integer-encoding = { version = "3.0.4" }
lalrpop-util = { version = "0.19.9" }
lazy_static = { version = "1.4.0" }
merlin = { version = "2" }
num-traits = { version = "0.2" }
polars = { version = "0.25.1" }
postcard = { version = "1.0" }
proofs = { path = "crates/proofs" } # We automatically update this line during release. So do not modify it!
proofs-sql = { path = "crates/proofs-sql" } # We automatically update this line during release. So do not modify it!
rand = { version = "0.7" }
rayon = { version = "1.5" }
regex = { version = "1" }
serde = { version = "1" }
thiserror = { version = "1" }
tracing = { version = "0.1.36" }
