[workspace]
resolver = "2"
members = ["crates/proofs", "crates/proofs-sql", "crates/proofs-wasm-test"]

[workspace.package]
edition = "2021"
exclude = ["**/.gitignore", ".gitignore"]
repository = "https://github.com/spaceandtimelabs/proofs"
version = "0.0.0" # DO NOT CHANGE THIS LINE! This will be automatically updated

[workspace.dependencies]
ark-bls12-381 = { version = "0.4.0" }
ark-curve25519 = { version = "0.4.0" }
ark-ec = { version = "0.4.0" }
ark-ff = { version = "0.4.0" }
ark-poly = { version = "0.4.0" }
ark-serialize = { version = "0.4.0" }
ark-std = { version = "0.4.0" }
arrayvec = { version = "0.7" }
arrow = { version = "45.0" }
arrow-csv = { version = "45.0" }
bit-iter = { version = "1.1.1" }
blake3 = { version = "1.3.3" }
blitzar = { version = "2.0.0" }
bumpalo = { version = "3.11.0" }
bytemuck = {version = "1.14.2" }
byte-slice-cast = { version = "1.2.1" }
clap = { version = "4.5.4" }
criterion = { version = "0.5.1" }
curve25519-dalek = { version = "4", features = ["rand_core"] }
derive_more = { version = "0.99" }
dyn_partial_eq = { version = "0.1.2" }
flexbuffers = { version = "2.0.0" }
hashbrown = { version = "0.14.0" }
indexmap = { version = "2.1" }
itertools = { version = "0.12.0" }
lalrpop-util = { version = "0.20.0" }
lazy_static = { version = "1.4.0" }
merlin = { version = "2" }
num-traits = { version = "0.2" }
num-bigint = { version = "0.4.4", default-features = false }
opentelemetry = { version = "0.22.0" }
opentelemetry-jaeger = { version = "0.20.0" }
polars = { version = "0.33.1", default-features = false }
postcard = { version = "1.0" }
proofs = { path = "crates/proofs" } # We automatically update this line during release. So do not modify it!
proofs-sql = { path = "crates/proofs-sql" } # We automatically update this line during release. So do not modify it!
rand = { version = "0.8" }
rand_core = { version = "0.6" }
rayon = { version = "1.5" }
serde = { version = "1" }
serde_json = { version = "1" }
thiserror = { version = "1" }
tracing = { version = "0.1.36" }
tracing-opentelemetry = { version = "0.22.0" }
tracing-subscriber = { version = "0.3.0" }
typetag = { version = "0.2.13" }
wasm-bindgen = { version = "0.2.92" }

[workspace.lints.rust]
missing_docs = "warn"