[profile.default]
src = "crates/proof-of-sql/src"
out = "crates/proof-of-sql/out"
solc = "0.8.17"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
