# Makes artifactory the default registry and saves passing --registry parameter
[registry]
default = "artifactory"

[registries.artifactory]
index = "https://spaceandtime.jfrog.io/artifactory/git/sxt-proofs-cargo-local.git"

# For sending credentials in git requests
[net]
git-fetch-with-cli = true

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang" # used to decrease build time
rustflags = ["-Clink-arg=-fuse-ld=lld"] # used to decrease link time
