[registries.artifactory]
index = "https://spaceandtime.jfrog.io/artifactory/git/sxt-proofs-cargo-local.git"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang" # used to decrease build time
rustflags = ["-Clink-arg=-fuse-ld=lld"] # used to decrease link time
