[package]
name = "proof-of-sql-planner"
edition.workspace = true
exclude.workspace = true
repository.workspace = true
version.workspace = true
license-file.workspace = true

[dependencies]
arrow = { workspace = true }
datafusion = '38.0.0'
indexmap = { workspace = true }
proof-of-sql = { path = "../proof-of-sql", features = ["arrow"] }
proof-of-sql-parser = { path = "../proof-of-sql-parser" }
snafu = { workspace = true }
sqlparser = { workspace = true }

[dev-dependencies]
bumpalo = { workspace = true }

[lints]
workspace = true
