[package]
name = "proofs"
version = "0.0.0" # This version will be automatically updated
edition = "2021"
repository = "https://github.com/spaceandtimelabs/proofs"
description = "Generates and verifies cryptographic proofs for SxT OLTP queries"
exclude = [
    "**/.gitignore",
    ".gitignore"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-ff = "^0.4.0"
ark-poly = "^0.4.0"
ark-std = "^0.4.0"
arrow = "28.0"
blake3 = "1.3.3"
bumpalo = { version = "3.11.0", features = ["collections"] }
byte-slice-cast = "1.2.1"
curve25519-dalek = { version = "3", features = ["serde"] }
dyn_partial_eq = "0.1.2"
hashbrown = "0.11.2"
indexmap = { version = "1.9", optional = true }
integer-encoding = "3.0.4"
merlin = "2"
num-traits = "0.2"
polars = { version = "0.25.1", features = ["lazy", "csv-file", "strings", "temporal", "dtype-duration", "dtype-categorical", "concat_str", "list_eval", "rank", "lazy_regex"], optional = true }
postcard = { version = "1.0", features = ["alloc"] }
proofs-gpu = { version = "7", registry = "artifactory" }
proofs-sql = { path = "../proofs-sql" } # We automatically update this line during release. So do not modify it!
rand = { version = "0.7", optional = true }
rayon = "1.5"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"
tracing = { version = "0.1.36", features = ["attributes"] }

[dev_dependencies]
criterion = "0.4"
indexmap = { version = "1.9" }
polars = { version = "0.25.1", features = ["lazy", "csv-file", "strings", "temporal", "dtype-duration", "dtype-categorical", "concat_str", "list_eval", "rank", "lazy_regex"] }
rand = { version = "0.7" }
rand_core = { version = "0.5" }
serde_json = "1"

[[bench]]
harness = false
name = "sumcheck"

[features]
default = []
test = ["dep:rand", "dep:polars", "dep:indexmap"]
