name: Python Lint (black)

# trigger for all PRs and changes to main
on:
  push:
    branches:
      - main
    paths:
      - '**/**.py'
      - '**/requirements.txt'
  pull_request:
    paths:
      - '**/**.py'
      - '**/requirements.txt'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
