name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    environment: deploy
    runs-on: large-8-core-32gb-22-04
    steps:
      # Load required tokens
      - name: Load secret
        uses: 1password/load-secrets-action@v1
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_CONNECT_HOST: ${{ secrets.OP_CONNECT_HOST }}
          OP_CONNECT_TOKEN: ${{ secrets.OP_CONNECT_TOKEN }}
          # Path to GitHub Credentials
          GH_TOKEN: op://op-github-devops/GH_TOKEN/proofs


      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ env.GH_TOKEN }}

      - run: git config --global --add safe.directory $(realpath .)

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Semantic Release
        run: |
          npm install semantic-release
          npx semantic-release
        env:
          GH_TOKEN: ${{ env.GH_TOKEN }}
