name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    environment: deploy
    runs-on: large-8-core-32gb-22-04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - run: git config --global --add safe.directory $(realpath .)

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Semantic Release
        run: |
          npm install semantic-release
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
