name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: read # for checkout
jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml

  release:
    name: Release
    runs-on: large-8-core-32gb-22-04
    needs: [lint-and-test]
    environment: deploy #!! DO NOT CHANGE THIS LINE !! #
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0 # download tags, see https://github.com/actions/checkout/issues/100
      - run: git config --global --add safe.directory $(realpath .)
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"
      - name: Install cargo info
        run: |
          cargo install cargo-info
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.0.0
      - name: Install dependencies
        run: solidity/scripts/install_deps.sh
      - name: Build generated solidity bundle
        run: |
          chmod +x solidity/scripts/pre_forge.sh
          solidity/scripts/pre_forge.sh build
          mkdir -p dist
          # adjust the source path to whatever pre_forge outputs:
          zip -r "dist/posql-generated.zip" solidity/src/base/Constants.sol solidity/src/base/Errors.sol solidity/src/client/ParamsBuilder.post.sol solidity/src/client/PoSQLTable.post.sol solidity/src/verifier/Verifier.post.sol

      - name: Semantic Release
        run: |
          npm install -D \
            semantic-release \
            @semantic-release/github \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator
          npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
          DEBUG: semantic-release:*,@semantic-release:*
